### ISSUE TITLE
Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by Bushwazi** [ben-eb/gulp-cssnano#30]
Not sure if I'm doing something wrong or if this is a legit bug.
Thanks

module.js:338
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/[PROJECT LOCATION]/node_modules/gulp-cssnano/node_modules/cssnano/index.js:17:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by ben-eb** [comment]
Not sure, perhaps your `npm install` failed to donwload autoprefixer? Try a reinstall.
