### ISSUE TITLE
Issues with Multiple Sourcemaps and Minified Styles

### ISSUE THREAD

**Issue by JeremyEnglert** [ben-eb/gulp-cssnano#38]
This may be related to: https://github.com/ben-eb/gulp-cssnano/issues/21 and https://github.com/ben-eb/gulp-cssnano/issues/35

I have a task that compiles all Sass files into minified AND non-minfied CSS files. I would also like to create Source Maps for both the minified and non-minified files.

This task runs, however, it doesn't create source maps for all of the minified files (it does some, but not all of them). Also, this task never shows as "finished", however, it does stop running. 
```
// Compile Sass, Autoprefix and minify
gulp.task('styles', function() {
    var source = gulp.src('./assets/scss/**/*.scss')
        .pipe(plumber(function(error) {
            gutil.log(gutil.colors.red(error.message));
            this.emit('end');
        }))
        .pipe(sourcemaps.init()) // Start Sourcemaps
        .pipe(sass())
        .pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        }));

    var stylesPipe1 = source.pipe(clone()) // Create non-minified sourcemap
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./assets/css/')); 

    var stylesPipe2 = source.pipe(clone()) // Create minified sourcemap
        .pipe(rename({suffix: '.min'}))
        .pipe(cssnano())
        .pipe(sourcemaps.write('.')) 
        .pipe(gulp.dest('./assets/css/'));

    return merge(stylesPipe1, stylesPipe2);
});  
```
Oddly enough, if `.pipe(sass())` is ran before `.pipe(sourcemaps.init())`, all of the sourcemaps are created. However, the sourcemaps are then referencing the CSS files instead of the Sass files.

Any ideas?

**Comment by ben-eb** [comment]
Can you try with gulp-postcss?

https://github.com/ben-eb/gulp-cssnano/issues/16#issuecomment-170343294

**Comment by JeremyEnglert** [comment]
That gives me the following error: `no writecb in Transform class`

Here's the code I used.

```
var gulp  = require('gulp'),
    gutil = require('gulp-util'),
    sass = require('gulp-sass'),
    cssnano = require('gulp-cssnano'),
    autoprefixer = require('gulp-autoprefixer'),
    sourcemaps = require('gulp-sourcemaps'),
    merge = require('merge-stream'),
    clone = require('gulp-clone'),
    postcss = require('gulp-postcss'),
    browserSync = require('browser-sync').create();

// Compile Sass, Autoprefix and minify
gulp.task('styles', function() {
    var source = gulp.src('./assets/scss/**/*.scss')
        .pipe(plumber(function(error) {
            gutil.log(gutil.colors.red(error.message));
            this.emit('end');
        }))
       .pipe(sourcemaps.init()) // Start Sourcemaps
        .pipe(sass())
        .pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        }));

    var stylesPipe1 = source.pipe(clone()) // Create non-minified sourcemap
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./assets/css/')); 

    var stylesPipe2 = source.pipe(clone()) // Create minified sourcemap
        .pipe(rename({suffix: '.min'}))
        .pipe(postcss([cssnano()]))
        .pipe(sourcemaps.write('.')) 
        .pipe(gulp.dest('./assets/css/'));

    return merge(stylesPipe1, stylesPipe2);
}); 
```

**Comment by ben-eb** [comment]
Try this one:

```js
var gulp  = require('gulp'),
    gutil = require('gulp-util'),
    sass = require('gulp-sass'),
    cssnano = require('cssnano'),
    autoprefixer = require('gulp-autoprefixer'),
    sourcemaps = require('gulp-sourcemaps'),
    jshint = require('gulp-jshint'),
    stylish = require('jshint-stylish'),
    uglify = require('gulp-uglify'),
    concat = require('gulp-concat'),
    rename = require('gulp-rename'),
    plumber = require('gulp-plumber'),
    bower = require('gulp-bower'),
    merge = require('merge-stream'),
    clone = require('gulp-clone'),
    postcss = require('gulp-postcss'),
    browserSync = require('browser-sync').create();

// Compile Sass, Autoprefix and minify
gulp.task('styles', function() {
    var source = gulp.src('./assets/scss/**/*.scss')
        .pipe(plumber(function(error) {
            gutil.log(gutil.colors.red(error.message));
            this.emit('end');
        }))
       .pipe(sourcemaps.init()) // Start Sourcemaps
        .pipe(sass())
        .pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        }));

    var stylesPipe1 = source.pipe(clone()) // Create non-minified sourcemap
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./assets/css/')); 

    var stylesPipe2 = source.pipe(clone()) // Create minified sourcemap
        .pipe(rename({suffix: '.min'}))
        .pipe(postcss([cssnano()]))
        .pipe(sourcemaps.write('.')) 
        .pipe(gulp.dest('./assets/css/'));

    return merge(stylesPipe1, stylesPipe2);
});
```

**Comment by JeremyEnglert** [comment]
No more error, but the issue persists. Here's a GIF what what's happening. Some files are created, but the styles.min.css isn't updated and the map isn't created.

Sorry about the delay at the beginning.

![zvwfmkh85b](https://cloud.githubusercontent.com/assets/6110968/13201104/579017e4-d820-11e5-8243-4d1b013b37a0.gif)

**Comment by kilianc** [comment]
+1 I am experiencing similar behavior with:

```
gulp.task('css', () => {
  return gulp.src('app/css/main.scss')
    .pipe(plugins.rename('bundle.min.css'))
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass({
      includePaths: ['styles'].concat(neat)
    }))
      .on('error', plugins.sass.logError)
    .pipe(plugins.postcss([
      require('postcss-assets')({
        loadPaths: ['images'],
        basePath: 'app',
        relative: true
      })
    ]))
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest('app'))
})

gulp.task('minify:css', () => {
  return gulp.src('app/bundle.min.css')
    .pipe(plugins.sourcemaps.init({ loadMaps: true }))
    .pipe(plugins.cssnano({
      discardComments: { removeAll: true }
    }))
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest('dist'))
})
```

Where `minify:css` starts and exits silently without printing "Finished" in the console.

**Comment by ben-eb** [comment]
@kilianc Does it output the minified CSS? What about if you try it without sourcemaps?

**Comment by kilianc** [comment]
it doesn't output the css and it works if I drop `loaMaps: true`. This may be related https://github.com/scniro/gulp-clean-css/issues/1

**Comment by kilianc** [comment]
@ben-eb finally got the time to create a self contained zip with a failing demo https://dl.dropboxusercontent.com/u/2208502/bug-sourcemaps.zip

let me know when you got it

**Comment by ben-eb** [comment]
@kilianc Got it. Changed the wrapper a bit now, got this error;

```js
[Error: "/node_modules/bourbon/app/assets/stylesheets/css3/_font-face.scss" is not in the SourceMap.]
{ [Error: "/node_modules/bourbon/app/assets/stylesheets/css3/_font-face.scss" is not in the SourceMap.]
  name: 'Error',
  message: '"/node_modules/bourbon/app/assets/stylesheets/css3/_font-face.scss" is not in the SourceMap.',
  stack: 'Error: "/node_modules/bourbon/app/assets/stylesheets/css3/_font-face.scss" is not in the SourceMap.\n    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/Users/beneb/Downloads/bug-sourcemaps/node_modules/source-map/lib/source-map-consumer.js:703:15)\n    at SourceMapGenerator.<anonymous> (/Users/beneb/Downloads/bug-sourcemaps/node_modules/source-map/lib/source-map-generator.js:229:42)\n    at Array.forEach (native)\n    at SourceMapGenerator_applySourceMap [as applySourceMap] (/Users/beneb/Downloads/bug-sourcemaps/node_modules/source-map/lib/source-map-generator.js:228:34)\n    at applySourceMap (/Users/beneb/Downloads/bug-sourcemaps/node_modules/vinyl-sourcemaps-apply/index.js:27:15)\n    at Transform.<anonymous> (/Users/beneb/Downloads/bug-sourcemaps/node_modules/gulp-cssnano/index.js:29:21)\n    at process._tickCallback (node.js:401:9)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-cssnano' }
```

**Comment by kilianc** [comment]
the problem is at https://github.com/ben-eb/gulp-cssnano/blob/master/index.js#L29 where `applySourceMap` is failing and the error is not properly handled in the promise chain. We should have a `.catch` at the end!

```
                if (result.map && file.sourceMap) {
                  try {
                    applySourceMap(file, String(result.map));
                  } catch (err) {
                    console.error(err)
                  }
                }
```

**Comment by kilianc** [comment]
@ben-eb fantastic how we drilled down the problem at the same time :) 👍

**Comment by ben-eb** [comment]
I don't understand, where is this problem coming from? Also, I'd prefer to call back with the error rather than handling it via console log. Something like this;

```js
function handleError (error) {
    var errorOptions = {fileName: file.path};
    if (error.name === 'CssSyntaxError') {
       error = error.message + error.showSourceCode();
       errorOptions.showStack = false;
    }
   // Prevent stream’s unhandled exception from
   // being suppressed by Promise
   setImmediate(function () {
       cb(new PluginError(PLUGIN_NAME, error));
   });
}
nano.process(String(file.contents), assign(opts, {
    map: (file.sourceMap) ? {annotation: false} : false,
    from: file.relative,
    to: file.relative
})).then(function (result) {
    if (result.map && file.sourceMap) {
        applySourceMap(file, String(result.map));
    }
    file.contents = new Buffer(result.css);
    this.push(file);
    cb();
}.bind(this), handleError).catch(handleError);
```

What do you think?

**Comment by kilianc** [comment]
@ben-eb that was just a snippet I posted to show where the error was being eaten. My proposed change was not to pass an error callback to `.then` but to chain a `.catch` so that you catch all errors in the first part of the chain.

`.then(fn, handleError).catch(handleError);` also works but you're passing the same handler twice :)

My suggestion would then be:

```js
stream._transform = function (file, encoding, cb) {
    if (file.isNull()) {
        return cb(null, file);
    }
    if (file.isStream()) {
        var error = 'Streaming not supported';
        return cb(new PluginError(PLUGIN_NAME, error));
    } else if (file.isBuffer()) {
        nano.process(String(file.contents), assign(opts, {
            map: (file.sourceMap) ? {annotation: false} : false,
            from: file.relative,
            to: file.relative
        })).then(function (result) {
            if (result.map && file.sourceMap) {
                applySourceMap(file, String(result.map));
            }
            file.contents = new Buffer(result.css);
            this.push(file);
            cb();
        }.bind(this))
        .catch(function (error) {
              var errorOptions = {fileName: file.path};
              if (error.name === 'CssSyntaxError') {
                 error = error.message + error.showSourceCode();
                 errorOptions.showStack = false;
              }
             // Prevent stream’s unhandled exception from
             // being suppressed by Promise
             setImmediate(function () {
                 cb(new PluginError(PLUGIN_NAME, error));
             });
        });
    }
};
```

**Comment by ben-eb** [comment]
OK, no problem. 👍

What about the error itself?

**Comment by kilianc** [comment]
It seems that [bourbon](bourbon.io) is not including something in the map file I am investigating, I am pretty sure that this has nothing to do with gulp-cssnano or gulp-sourcemaps, it's bourbon or me.

**Comment by ben-eb** [comment]
Thanks for providing the test case. I pushed a fix for this that should help anyone else running into sourcemap conflicts. 👍

**Comment by kilianc** [comment]
@ben-eb let me know if I should kick a new issue for this. 

It appears that after processing https://github.com/ben-eb/gulp-cssnano/blob/master/index.js#L23 the sources get all overwritten and I think this is what is causing the error. If I do `console.log(JSON.parse(String(result.map)).sources)` I get  `[ 'bundle.min.css' ]`. Instead of all my previous sources? I see them being there in `file.sourceMap.sources`.

**Comment by ben-eb** [comment]
Yes, if it is a problem with how we handle source maps.

**Comment by kilianc** [comment]
I am going down the dependency tree and it may not be related, it looks like there are issues with relative paths, I have `"../../node_modules/bourbon/app/assets/stylesheets/css3/_font-face.scss"` and `source-map` looks for `"/node_modules/bourbon/app/assets/stylesheets/css3/_font-face.scss"`
