### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by MatthewHerbst** [ben-eb/gulp-cssnano#40]
Node `v0.10.36`
npm `v1.3.6`

After doing `npm install --save-dev gulp-cssnano` and trying to run my build process (`npm run build` => `gulp build`), I got:

```
/home/xxxxxx/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/home/xxxxxx/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/xxxxxx/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/lazy-result.js:79:21)
    at Transform.stream._transform (/home/xxxxxx/node_modules/gulp-cssnano/index.js:27:17)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Transform.Writable.write (_stream_writable.js:183:11)
    at DestroyableTransform.ondata (/home/xxxxxx/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:583:20)
    at DestroyableTransform.emit (events.js:95:17)
npm ERR! weird error 8
npm ERR! not ok code 0
```

I was able to fix this by including

```
require('es6-promise').polyfill();
```

at the top of my gulpfile. [Props to @jbq over at css-loader for the fix](https://github.com/webpack/css-loader/issues/144#issuecomment-171265235).

**Comment by ben-eb** [comment]
Yeah, I don't support less than node 0.12 - remember that node version 5 is out with many more fixes, methods and performance increases. But loading a polyfill is acceptable if you're stuck with 0.10. :smile:
