### ISSUE TITLE
An error occurred in the linux 

### ISSUE THREAD

**Issue by twang281314** [ben-eb/gulp-cssnano#54]
```
var gulp=require('gulp');
var miniCss = require('gulp-cssnano');
var clean = require('gulp-clean');


gulp.task('clean', function() {
    return gulp.src('dist', {
            read: false
        })
        .pipe(clean());
});
```
in the linux error occurred ,but windows have no the problem
```
[15:50:37] Using gulpfile /jenkins/workspace/Dev_WEB/gulpfile.js
[15:50:37] Starting 'build'...
[15:50:37] Starting 'clean'...
[15:50:37] 'clean' errored after 4.8 ms
[15:50:37] TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_module                   s/glob2base/index.js:9:25)
    at setToBase (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/                   glob2base/index.js:48:12)
    at module.exports (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_mod                   ules/glob2base/index.js:56:19)
    at Object.gs.createStream (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/                   index.js:34:42)
    at Object.gs.create (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.                   js:68:42)
    at Gulp.src (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/jenkins/workspace/Dev_WEB/gulpfile.js:490:17)
    at module.exports (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/jenkins/workspace/Dev_WEB/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```

**Comment by jdubois** [comment]
We're having the same issue here:
https://github.com/jhipster/generator-jhipster/issues/4016

Broke everything, for a lot of people :-(
Why don't use fixed dependencies? That was bound to happen.

**Comment by cronfy** [comment]
Same problem. Steps to reproduce with clean setup:

```
# new user

sudo adduser --disabled-password --gecos "" username
sudo su - nanotest


# node

git clone https://github.com/basherpm/basher.git ~/.basher
echo 'export PATH="$HOME/.basher/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(basher init -)"' >> ~/.bash_profile

. ~/.bash_profile

basher install isaacs/nave

nave use stable

npm install --global npm
npm install --global gulp-cli

# project

cd 
mkdir tmp
cd tmp
mkdir project
cd project
mkdir src css
echo "h1 { font-weight: bold }" > src/style.css

cat << EOF > package.json
{
  "name": "project",
  "version": "1.0.0",
  "description": "Test gulp-cssnano",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-cssnano": "^2.1.2"
  }
}
EOF

npm install

cat << EOF > gulpfile.js
var gulp = require('gulp');
var cssnano = require('cssnano');

gulp.task('default', function() {
  return gulp.src('src/*.css');
});
EOF

# run

gulp
```

Output:

```
nanotest@layoone ~/tmp/project $ gulp
(node:18193) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[12:43:19] Using gulpfile ~/tmp/project/gulpfile.js
[12:43:19] Starting 'default'...
[12:43:19] 'default' errored after 4.61 ms
[12:43:19] TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/home/nanotest/tmp/project/node_modules/glob2base/index.js:9:25)
    at setToBase (/home/nanotest/tmp/project/node_modules/glob2base/index.js:48:12)
    at module.exports (/home/nanotest/tmp/project/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/home/nanotest/tmp/project/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/home/nanotest/tmp/project/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/home/nanotest/tmp/project/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/home/nanotest/tmp/project/gulpfile.js:5:15)
    at module.exports (/home/nanotest/tmp/project/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/nanotest/tmp/project/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/nanotest/tmp/project/node_modules/orchestrator/index.js:214:10)
```

**Comment by elensky** [comment]
The same problem.

**Comment by KayVollers** [comment]
The problem seems to come from reduce-css-calc which is indirectly used, see here:
https://github.com/MoOx/reduce-css-calc/issues/13

**Comment by Phalconline** [comment]
Check it https://github.com/gulpjs/gulp/issues/1768

**Comment by TheSpyder** [comment]
This has been fixed upstream, delete `node_modules` and reinstall should work now

**Comment by ben-eb** [comment]
> Why don't use fixed dependencies? That was bound to happen.

So that we can benefit from features and bug fixes that our dependencies have. Indeed, it's unfortunate that sometimes this can lead to unexpected breaks, but a critical security issue was patched in cssnano by virtue of the semver promise. Just happy that this was resolved quickly by all parties involved. 🎉

**Comment by TheSpyder** [comment]
Yeah. In this case, a critical security fix in one of the `postcss-calc` libraries introduced a major bug, and the developer decided to wait for _his_ upstream to fix the bug as he deemed the security issue to be more severe.
