### ISSUE TITLE
Getting error on cssnano dependency. 

### ISSUE THREAD

**Issue by parkej60** [ben-eb/gulp-cssnano#57]
Seems to be an error with the latest CSSNano Build.
```
gulp-cssnano/node_modules/cssnano/node_modules/postcss-svgo/node_modules/svgo/plugins/cleanupIDs.js:123
for (var ID of referencesIDs) {
^^
SyntaxError: Unexpected identifier
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
```

**Comment by parkej60** [comment]
This can be closed it looks like SVGO is now requiring a minimum of nvm 0.12.
