### ISSUE TITLE
gulp --production returns SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by bertalanimre** [ben-eb/gulp-cssnano#58]
Hello,

When I run `gulp --production` on my laravel website I get the following error:

```
/var/www/hu.mycompany.test/node_modules/laravel-elixir/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-svgo/node_modules/svgo/plugins/cleanupIDs.js:123
    for (var ID of referencesIDs) {
                ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /var/www/hu.mycompany.test/node_modules/laravel-elixir/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-svgo/node_modules/svgo/lib/svgo/config.js:99:33
    at Array.map (native)
    at preparePluginsArray (/var/www/hu.mycompany.test/node_modules/laravel-elixir/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-svgo/node_modules/svgo/lib/svgo/config.js:64:20)
    at module.exports (/var/www/hu.mycompany.test/node_modules/laravel-elixir/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-svgo/node_modules/svgo/lib/svgo/config.js:32:28)
```

Have you met this error before or do you have any clue what could be wrong?

My servers spec. is:
CentOS 7
Node -v -> v0.10.46

**Comment by ben-eb** [comment]
Your issue is being caused by a soon to be end-of-lifed Node.js version; from October there will be no new updates for this version. I recommend upgrading to at least Node 4.

https://github.com/ben-eb/postcss-svgo/issues/47#issuecomment-248160592
